---
title: "Pareto efficiency analysis in RWebPPL"
author: "Larry Liu and Michael C. Frank"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: true
number_sections: true
---
  
```{r, echo = FALSE, include = FALSE}
rm(list=ls())
library(tidyverse)
library(rwebppl)
library(knitr)
opts_chunk$set(echo=FALSE, cache=TRUE, warning=FALSE, message = FALSE)
theme_set(theme_bw())
```

# Pipeline sanity check
```{r}
test_model <- "
var model = function() {
  console.log(\"Hello world\")
  return mathBeta.beta(3,5);
}
model();
"
webppl(test_model, packages = c("webppl/node_modules/webppl-beta"))

```

# Single student

```{r}
out <- as.data.frame(webppl(program_file = "webppl/scripts/bayesianTeacher.js", packages = c("webppl/node_modules/webppl-compute-digamma/", "webppl/node_modules/webppl-beta")))
```

Write the data to an intermediate caching csv for external/reproducibility use

```{r}
write.csv(out, file='raw_data.csv')
```

Load packages for simulations
```{r}
library('tidyverse')
library('ggplot2')
library('Rmisc')
```

Try running a simulation
```{r}

```

# Single student with teacher

```{r}
out <- webppl(program_file = "webppl/single_student.js")
```

We select HMC as our inference method, revisit this. 

Plot output. 

```{r}
qplot(support, prob, data = out) + 
  xlim(c(0,1)) + 
  ylim(c(0,max(out$prob)))
```

# Single student with teacher

```{r}
out <- webppl(program_file = "webppl/single_student_with_teacher.js")
```

We select HMC as our inference method, revisit this. 

Plot output. 

```{r}
qplot(support, prob, data = out) + 
  xlim(c(0,1)) + 
  ylim(c(0,max(out$prob)))
```
