---
title: "Pareto efficiency analysis in RWebPPL"
author: "Larry Liu and Michael C. Frank"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: true
number_sections: true
---
  
```{r, echo = FALSE, include = FALSE}
rm(list=ls())
library(tidyverse)
library(rwebppl) #requires devtools::install_github("mhtess/rwebppl")
library(knitr)
opts_chunk$set(echo=FALSE, cache=TRUE, warning=FALSE, message = FALSE)
theme_set(theme_bw())
```

# Pipeline sanity check
```{r}
#if this code block fails to execute because the packages cannot be found, navigate to sims_admin/node_modules/webppl-beta and sims_admin/node_modules/webppl-compute-digamma in the Terminal and run the following command (including final period)
# npm install --prefix ~/.webppl .

test_model <- "
var model = function() {
  console.log(\"Hello world\")
  return IG2(1,2,3,4,5,6);
  //return mathBeta.beta(3,5);
}
model();
"
webppl(test_model, packages = c("math-beta", "webppl-compute-digamma"))
#webppl(test_model, packages = c("sims_admin/node_modules/webppl-beta", "sims_admin/node_modules/webppl-compute-digamma"))

```

# Single student

```{r}
startTimeSmall100 <- Sys.time()
out1 <- as.data.frame(webppl(program_file = "~/Documents/teaching/sims_admin/scripts/bayesianTeacher.js", packages = c("math-beta", "webppl-compute-digamma")))
out2 <- as.data.frame(webppl(program_file = "~/Documents/teaching/sims_admin/scripts/bayesianTeacher.js", packages = c("math-beta", "webppl-compute-digamma")))
out3 <- as.data.frame(webppl(program_file = "~/Documents/teaching/sims_admin/scripts/bayesianTeacher.js", packages = c("math-beta", "webppl-compute-digamma")))
out4 <- as.data.frame(webppl(program_file = "~/Documents/teaching/sims_admin/scripts/bayesianTeacher.js", packages = c("math-beta", "webppl-compute-digamma")))
out5 <- as.data.frame(webppl(program_file = "~/Documents/teaching/sims_admin/scripts/bayesianTeacher.js", packages = c("math-beta", "webppl-compute-digamma")))
out2$trialNum = out2$trialNum + 20
out3$trialNum = out3$trialNum + 40
out4$trialNum = out4$trialNum + 60
out5$trialNum = out5$trialNum + 80
out <- rbind(out1, out2, out3, out4, out5)
endTimeSmall100 <- Sys.time()
```

```{r}
out3Per11Nu <- as.data.frame(webppl(program_file = "~/Documents/teaching/sims_admin/scripts/bayesianTeacher.js", packages = c("math-beta", "webppl-compute-digamma")))
write_csv(out3Per, "cached_data/raw_data_013117_3Per11Nu_small.csv")
```

Write the data to an intermediate caching csv for external/reproducibility use

```{r}
#write.csv(out, file='raw_data.csv')
#write_csv(out, path=cat('raw_data_', as.character(Sys.Date()), '.csv', sep=''))
#filename <- cat('raw_data_', as.character(Sys.Date()), '.csv',sep='')
write_csv(out1, "cached_data/raw_data_013117.csv")
#write_csv(out, filename)
```

Load packages for simulations
```{r}
library('tidyverse')
library('ggplot2')
library('Rmisc')
```

Load data for simulations
```{r}
df <- read.csv(file = 'cached_data/raw_data.csv')
```
